### ISSUE TITLE
Throws Exception 'XMLStream' object has no attribute '_writer'

### ISSUE THREAD

**Issue by chandrapavanjitta** [Fatal1ty/aiofcm#3]
On running this code with numeric_sender_id, api_key and device_token, **Throws error XMLStream object has no attribute '_write'**

```
from uuid import uuid4
from aiofcm import FCM, Message, PRIORITY_HIGH


async def run():
    fcm = FCM('<NUMERICAL_SENDER_ID>', '<API_KEY>')
    message = Message(
        device_token='<DEVICE_TOKEN>',
        notification={           # optional
            "title": "Hello from Firebase",
            "body": "This is notification",
            "sound": "default"
        },
        data={"score": "3x1"},   # optional
        message_id=str(uuid4())  # optional
        time_to_live=3,          # optional
        priority=PRIORITY_HIGH,  # optional
    )
    await fcm.send_message(message)

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aioopenssl/__init__.py", line 319, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1716, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1456, in _raise_ssl_error
    _raise_current_error()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
'XMLStream' object has no attribute '_writer'
```

Is there any way to solve this issue or is it a BUG ?

**Comment by Fatal1ty** [comment]
@beastreload could you show me `pip freeze` output?
